### ISSUE TITLE
Compilation errors on macOS

### ISSUE THREAD

**Issue by jacobpwagner** [RGLab/RProtoBufLib#13]
Hey @mikejiang  and @gfinak, just a heads up that I ran in to some simple compilation errors on macOS Big Sur with the most recent `master` branch. Fortunately the errors were really informative and the gist was:
```
Protobuf requires at least c++11
```
I think it's just that clang wasn't supporting C++11 features by default. Anyway, adding `CXX_STD = CXX11` to [`Makevars.in`](https://github.com/RGLab/RProtoBufLib/blob/master/src/Makevars.in) fixed it right up. Just a heads up in case you start getting Mac build failures.

**Comment by mikejiang** [comment]
@jacobpwagner , thanks for the help!

**Comment by jacobpwagner** [comment]
Looks good via `devtools::install_github("RGLab/RProtoBufLib")` after 6fd8eed. Thanks!
