### ISSUE TITLE
Build error on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by robby81** [RGLab/RProtoBufLib#3]
See the log here: http://paste.opensuse.org/85901062

**Comment by mikejiang** [comment]
looks like default `libdir` is set to `lib64` in your system , hopefully it can be overridden by `configure` script.
Let me know if you can install it now through  `devtools::install_github("RGLab/RProtoBufLib")`

**Comment by robby81** [comment]
Thank you a lot. Now it worked, however with `install_github("RGLab/RProtoBufLib@trunk")`. Thus the issue can be closed.
